### ISSUE TITLE
9.6.2 upgrade

### ISSUE THREAD

**Issue by fboucquez** [IoDLT/cat-install-scripts#1]
Hi team, thank you for the scripts. They are great!

I'm trying to run 0.9.6.2 locally but I can see these scripts haven't been updated since v0.9.4.1. Would updating the CATAPULT_VERSION do the trick or is it any other lib/script that needs upgrading? I'm able to compile by just changing the version (or pulling the latest code from catapult-server) but I'm asking just in case it's not enough.  

Also, I would recommend keeping the master branch to the latest version (in this case v0.9.4.1 or better v0.9.4.2 if it can be upgraded). It took me some time to figure out that there is a newer version with newer documentation in another branch. I guess other people may have the same problem. 

Thanks!

**Comment by CrackTheCode016** [comment]
Hi!

Yes, changing catapult version should be enough.  iirc, there is nothing that changed with dependencies that warrants any changes.  You're right on the master branch - I'll get that merged asap.  

Thank you!!

**Comment by fboucquez** [comment]
Thanks @CrackTheCode016. What about adding the CATAPULT_VERSION as a bash param? If there aren't script dependency changes between versions, the same cat-install-scripts master may work for future versions (no need to upgrade them). Docs would need updating. 

The downside is the scripts may not be that explicit. If there are dependency changes or devs want to compile an old server version, they may have some issues.

**Comment by CrackTheCode016** [comment]
That's a really good suggestion - I'll try to work something out for that in the next week.  For minor versions, i.e `0.9.6.2` -> `0.9.6.3` it should not be an issue, and it would even allow for the compiling of older server versions in some cases.  Overall, I think it would make a good addition 👍  

Thank for you so much for the feedback

**Comment by CrackTheCode016** [comment]
fixed in 8e47871
